/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qdating_publisher_LSPublisherJni */

#ifndef _Included_net_qdating_publisher_LSPublisherJni
#define _Included_net_qdating_publisher_LSPublisherJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    Create
 * Signature: (Lnet/qdating/publisher/ILSPublisherCallbackJni;Lnet/qdating/publisher/ILSVideoEncoderJni;IIIII)J
 */
JNIEXPORT jlong JNICALL Java_net_qdating_publisher_LSPublisherJni_Create
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_Destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    PublishUrl
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_qdating_publisher_LSPublisherJni_PublishUrl
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    PushVideoFrame
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_PushVideoFrame
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    Stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_Stop
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
