/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qdating_LSPlayerJni */

#ifndef _Included_net_qdating_LSPlayerJni
#define _Included_net_qdating_LSPlayerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qdating_LSPlayerJni
 * Method:    GobalInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_qdating_LSPlayerJni_GobalInit
  (JNIEnv *, jclass);

/*
 * Class:     net_qdating_LSPlayerJni
 * Method:    Create
 * Signature: (Lnet/qdating/ILSPlayerCallbackJni;Lnet/qdating/ILSVideoRendererJni;Lnet/qdating/ILSAudioRendererJni;Lnet/qdating/ILSVideoDecoderJni;)J
 */
JNIEXPORT jlong JNICALL Java_net_qdating_LSPlayerJni_Create
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     net_qdating_LSPlayerJni
 * Method:    Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_qdating_LSPlayerJni_Destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_qdating_LSPlayerJni
 * Method:    PlayUrl
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_qdating_LSPlayerJni_PlayUrl
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     net_qdating_LSPlayerJni
 * Method:    Stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_qdating_LSPlayerJni_Stop
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
