/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qdating_LSPublisherJni */

#ifndef _Included_net_qdating_LSPublisherJni
#define _Included_net_qdating_LSPublisherJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qdating_LSPublisherJni
 * Method:    GobalInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_qdating_LSPublisherJni_GobalInit
  (JNIEnv *, jclass);

/*
 * Class:     net_qdating_LSPublisherJni
 * Method:    Create
 * Signature: (Lnet/qdating/ILSPublisherCallbackJni;)J
 */
JNIEXPORT jlong JNICALL Java_net_qdating_LSPublisherJni_Create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_qdating_LSPublisherJni
 * Method:    Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_qdating_LSPublisherJni_Destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_qdating_LSPublisherJni
 * Method:    PublishUrl
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_qdating_LSPublisherJni_PublishUrl
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring);

/*
 * Class:     net_qdating_LSPublisherJni
 * Method:    Stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_qdating_LSPublisherJni_Stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_qdating_LSPublisherJni
 * Method:    SendVideoFrame
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_net_qdating_LSPublisherJni_SendVideoFrame
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     net_qdating_LSPublisherJni
 * Method:    SendAudioFrame
 * Signature: (JIII[BI)V
 */
JNIEXPORT void JNICALL Java_net_qdating_LSPublisherJni_SendAudioFrame
  (JNIEnv *, jobject, jlong, jint, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
