/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_utils_CrashHandlerJni */

#ifndef _Included_com_qpidnetwork_utils_CrashHandlerJni
#define _Included_com_qpidnetwork_utils_CrashHandlerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_utils_CrashHandlerJni
 * Method:    SetCrashLogDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_anchor_utils_CrashHandlerJni_SetCrashLogDirectory
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
