platform :ios, '8.0'

#使用动态连接
#use_frameworks!

target 'livestream' do
	pod 'GPUImage', '~> 0.1.7'
	pod 'AFNetworking', '~> 3.0.4'
	pod 'SDWebImage', '~> 4.0.0'
	pod 'Masonry', '~> 0.6.4'
	pod 'TTTAttributedLabel', '~> 2.0.0'
	pod 'Google/Analytics'
end