/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_anchor_httprequest_RequestJniLiveShow */

#ifndef _Included_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
#define _Included_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
 * Method:    GetAudienceListInRoom
 * Signature: (Ljava/lang/String;IILcom/qpidnetwork/livemodule/httprequest/OnGetAudienceListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow_GetAudienceListInRoom
  (JNIEnv *, jclass, jstring, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
 * Method:    GetAudienceDetailInfo
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnGetAudienceDetailInfoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow_GetAudienceDetailInfo
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
 * Method:    GetAllGiftList
 * Signature: (Lcom/qpidnetwork/livemodule/httprequest/OnGetGiftListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow_GetAllGiftList
        (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
 * Method:    GiftLimitNumList
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnGiftLimitNumListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow_GiftLimitNumList
        (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
 * Method:    GetGiftDetail
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnGetGiftDetailCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow_GetGiftDetail
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
 * Method:    GetEmotionList
 * Signature: (Lcom/qpidnetwork/livemodule/httprequest/OnGetEmotionListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow_GetEmotionList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
 * Method:    DealTalentRequest
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/livemodule/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow_DealTalentRequest
        (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
 * Method:    DealTalentRequest
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/livemodule/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow_DealTalentRequest
        (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
 * Method:    SetAutoPush
 * Signature: (ILcom/qpidnetwork/anchor/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow_SetAutoPush
        (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniLiveShow
 * Method:    GetCurrentRoomInfo
 * Signature: (ILcom/qpidnetwork/anchor/httprequest/OnGetCurrentRoomInfoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniLiveShow_GetCurrentRoomInfo
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
