/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_anchor_httprequest_RequestJniHangout */

#ifndef _Included_com_qpidnetwork_anchor_httprequest_RequestJniHangout
#define _Included_com_qpidnetwork_anchor_httprequest_RequestJniHangout
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniHangout
 * Method:    GetCanRecommendFriendList
 * Signature: (IILcom/qpidnetwork/anchor/httprequest/OnGetAnchorListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniHangout_GetCanRecommendFriendList
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniHangout
 * Method:    RecommendFriendJoinHangout
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/anchor/httprequest/OnRecommendFriendCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniHangout_RecommendFriendJoinHangout
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniHangout
 * Method:    DealInvitationHangout
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/anchor/httprequest/OnDealInvitationHangoutCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniHangout_DealInvitationHangout
        (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniHangout
 * Method:    GetOngoingHangoutList
 * Signature: (IILcom/qpidnetwork/anchor/httprequest/OnGetOngoingHangoutListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniHangout_GetOngoingHangoutList
        (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniHangout
 * Method:    SendKnockRequest
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/anchor/httprequest/OnGetSendKnockRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniHangout_SendKnockRequest
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniHangout
 * Method:    GetHangoutKnockStatus
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/anchor/httprequest/OnGetHangoutKnockStatusCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniHangout_GetHangoutKnockStatus
  (JNIEnv *, jclass, jstring, jobject);


/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniHangout
 * Method:    CancelHangoutKnock
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/anchor/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniHangout_CancelHangoutKnock
        (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniHangout
 * Method:    HangoutGiftList
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/anchor/httprequest/OnHangoutGiftListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniHangout_HangoutGiftList
        (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniHangout
 * Method:    AddAnchorFriend
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/anchor/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniHangout_AddAnchorFriend
        (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniHangout
 * Method:    GetHangoutFriendRelation
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/anchor/httprequest/OnGetHangoutFriendRelationCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniHangout_GetHangoutFriendRelation
        (JNIEnv *, jclass, jstring, jobject);


#ifdef __cplusplus
}
#endif
#endif
