/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_anchor_httprequest_RequestJniOther */

#ifndef _Included_com_qpidnetwork_anchor_httprequest_RequestJniOther
#define _Included_com_qpidnetwork_anchor_httprequest_RequestJniOther
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniOther
 * Method:    SynConfig
 * Signature: (Lcom/qpidnetwork/livemodule/httprequest/OnSynConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniOther_SynConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniOther
 * Method:    GetTodayCredit
 * Signature: (Lcom/qpidnetwork/livemodule/httprequest/OnGetTodayCreditCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniOther_GetTodayCredit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniOther
 * Method:    ServerSpeed
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/livemodule/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniOther_ServerSpeed
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_anchor_httprequest_RequestJniOther
 * Method:    UploadCrashFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnRequestLSUploadCrashFileCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_anchor_httprequest_RequestJniOther_UploadCrashFile
        (JNIEnv *, jclass, jstring, jstring, jstring, jobject);


#ifdef __cplusplus
}
#endif
#endif
