/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_livemodule_httprequest_RequestJniSetting */

#ifndef _Included_com_qpidnetwork_livemodule_httprequest_RequestJniSetting
#define _Included_com_qpidnetwork_livemodule_httprequest_RequestJniSetting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniSetting
 * Method:    GetPushConfig
 * Signature: (Lcom/qpidnetwork/livemodule/httprequest/OnGetGetPushConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniSetting_GetPushConfig
  (JNIEnv *, jclass,  jobject);

  /*
   * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniSetting
   * Method:    SetPushConfig
   * Signature: (ZZLcom/qpidnetwork/livemodule/httprequest/OnRequestCallback;)J
   */
  JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniSetting_SetPushConfig
    (JNIEnv *, jclass,  jboolean, jboolean, jobject);


#ifdef __cplusplus
}
#endif
#endif
