/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_livemodule_httprequest_RequestJniPrivateMsg */

#ifndef _Included_com_qpidnetwork_livemodule_httprequest_RequestJniPrivateMsg
#define _Included_com_qpidnetwork_livemodule_httprequest_RequestJniPrivateMsg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniOther
 * Method:    SynConfig
 * Signature: (Lcom/qpidnetwork/livemodule/httprequest/OnSynConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniPrivateMsg_GetPrivateMsgFriendList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniOther
 * Method:    GetAccountBalance
 * Signature: (Lcom/qpidnetwork/livemodule/httprequest/OnGetAccountBalanceCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniPrivateMsg_GetFollowPrivateMsgFriendList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniOther
 * Method:    AddOrCancelFavorite
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLcom/qpidnetwork/livemodule/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniPrivateMsg_GetPrivateMsgHistoryById
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jlong);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniOther
 * Method:    SetPrivateMsgReaded
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLcom/qpidnetwork/livemodule/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniPrivateMsg_SetPrivateMsgReaded
        (JNIEnv *, jclass, jstring, jstring, jlong);


#ifdef __cplusplus
}
#endif
#endif
