/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat */

#ifndef _Included_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
#define _Included_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    CheckCoupon
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/request/OnCheckCouponCallCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_CheckCoupon
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    UseCoupon
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/request/OnLCUseCouponCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_UseCoupon
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    QueryChatVirtualGift
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnQueryChatVirtualGiftCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_QueryChatVirtualGift
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    QueryChatRecord
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnQueryChatRecordCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_QueryChatRecord
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    QueryChatRecordMutiple
 * Signature: ([Ljava/lang/String;Lcom/qpidnetwork/request/OnQueryChatRecordMutipleCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_QueryChatRecordMutiple
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    SendPhoto
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnLCSendPhotoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_SendPhoto
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    PhotoFee
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnLCPhotoFeeCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_PhotoFee
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    GetPhoto
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;Lcom/qpidnetwork/request/OnLCGetPhotoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_GetPhoto
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring, jint, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    UploadVoice
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;ILjava/lang/String;ILjava/lang/String;Lcom/qpidnetwork/request/OnLCUploadVoiceCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_UploadVoice
  (JNIEnv *, jclass, jstring, jstring, jstring, jboolean, jstring, jint, jstring, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    PlayVoice
 * Signature: (Ljava/lang/String;ILjava/lang/String;Lcom/qpidnetwork/request/OnLCPlayVoiceCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_PlayVoice
  (JNIEnv *, jclass, jstring, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    SendGift
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_SendGift
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    QueryRecentVideo
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnQueryRecentVideoListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_QueryRecentVideo
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    GetVideoPhoto
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Lcom/qpidnetwork/request/OnRequestFileCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_GetVideoPhoto
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    GetVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Lcom/qpidnetwork/request/OnLCGetVideoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_GetVideo
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    GetMagicIconConfig
 * Signature: (Lcom/qpidnetwork/request/OnGetMagicIconConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_GetMagicIconConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    ChatRecharge
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnLCChatRechargeCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_ChatRecharge
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    GetThemeConfig
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnGetThemeConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_GetThemeConfig
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    GetThemeDetail
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnGetThemeDetailCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_GetThemeDetail
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat
 * Method:    CheckFunctions
 * Signature: ([IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnCheckFunctionsCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniLiveChat_CheckFunctions
  (JNIEnv *, jclass, jintArray, jint, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
