/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_livemodule_httprequest_RequestJni */

#ifndef _Included_com_qpidnetwork_livemodule_httprequest_RequestJni
#define _Included_com_qpidnetwork_livemodule_httprequest_RequestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    SetLogDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_SetLogDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    SetVersionCode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_SetVersionCode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    SetCookiesDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_SetCookiesDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    SetWebSite
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_SetWebSite
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    SetPhotoUploadSite
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_SetPhotoUploadSite
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    SetConfigSite
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_SetConfigSite
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    StopRequest
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_StopRequest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    GetLocalMacMD5
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_GetLocalMacMD5
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    SetDeviceId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_SetDeviceId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    CleanCookies
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_CleanCookies
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    GetCookiesItem
 * Signature: ()["com/qpidnetwork/livemodule/httprequest/item/CookiesItem";
 */
JNIEXPORT jobjectArray JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_GetCookiesItem
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
 * Method:    SetProxy
 * Signature: (Ljava/lang/String;I)V
 * add by Jagger 2018-2-22
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJni_SetProxy
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
