/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther */

#ifndef _Included_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
#define _Included_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
#ifdef __cplusplus
extern "C" {
#endif
#undef com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeCL
#define com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeCL 1L
#undef com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeIDA
#define com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeIDA 2L
#undef com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeCD
#define com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeCD 4L
#undef com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeLA
#define com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeLA 8L
#undef com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeAll
#define com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeAll 0L
#undef com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeUnknow
#define com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SiteTypeUnknow 0L
/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
 * Method:    EmotionConfig
 * Signature: (Lcom/qpidnetwork/request/OnOtherEmotionConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_EmotionConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
 * Method:    GetCount
 * Signature: (ZZZZZZLcom/qpidnetwork/request/OnOtherGetCountCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_GetCount
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jobject);

///*
// * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
// * Method:    PhoneInfo
// * Signature: (Ljava/lang/String;ILjava/lang/String;IIDIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;Lcom/qpidnetwork/request/OnOtherPhoneInfoCallback;)J
// */
//JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_PhoneInfo
//  (JNIEnv *, jclass, jstring, jint, jstring, jint, jint, jdouble, jint, jint, jstring, jstring, jstring, jstring, jstring, jint, jint, jstring, jobject);
//
///*
// * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
// * Method:    IntegralCheck
// * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnOtherIntegralCheckCallback;)J
// */
//JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_IntegralCheck
//  (JNIEnv *, jclass, jstring, jobject);
//
///*
// * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
// * Method:    VersionCheck
// * Signature: (ILcom/qpidnetwork/request/OnOtherVersionCheckCallback;)J
// */
//JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_VersionCheck
//  (JNIEnv *, jclass, jint, jstring, jobject);
//
///*
// * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
// * Method:    SynConfig
// * Signature: (Lcom/qpidnetwork/request/OnOtherSynConfigCallback;)J
// */
//JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_SynConfig
//  (JNIEnv *, jclass, jobject);
//
///*
// * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
// * Method:    OnlineCount
// * Signature: (ILcom/qpidnetwork/request/OnOtherOnlineCountCallback;)J
// */
//JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_OnlineCount
//  (JNIEnv *, jclass, jint, jobject);
//
///*
// * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
// * Method:    UploadCrashLog
// * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
// */
//JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_UploadCrashLog
//  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);
//
///*
// * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther
// * Method:    InstallLogs
// * Signature: (Ljava/lang/String;IIJJILjava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
// */
//JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJniOther_InstallLogs
//  (JNIEnv *, jclass, jstring, jint, jint, jlong, jlong, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
