/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_livemodule_httprequest_RequestJniPayment */

#ifndef _Included_com_qpidnetwork_livemodule_httprequest_RequestJniPayment
#define _Included_com_qpidnetwork_livemodule_httprequest_RequestJniPayment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniPayment
 * Method:    MobilePayGoto
 * Signature: (ILjava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnMobilePayGotoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniPayment_MobilePayGoto
  (JNIEnv *, jclass, jint, jstring , jstring , jobject);



#ifdef __cplusplus
}
#endif
#endif
