/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower */

#ifndef _Included_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
#define _Included_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    GetStoreGiftList
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnGetPackageGiftListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_GetStoreGiftList
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    GetFlowerGiftDetail
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnGetVouchersListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_GetFlowerGiftDetail
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    GetRecommendGiftList
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILcom/qpidnetwork/livemodule/httprequest/OnGetRidesListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_GetRecommendGiftList
  (JNIEnv *, jclass, jstring, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    GetResentRecipientList
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_GetResentRecipientList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    GetDeliveryList
 * Signature: (Lcom/qpidnetwork/livemodule/httprequest/OnGetPackageUnreadCountCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_GetDeliveryList
        (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    GetCartGiftTypeNum
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnGetVoucherAvailableInfoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_GetCartGiftTypeNum
        (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    GetCartGiftList
 * Signature: (IILcom/qpidnetwork/livemodule/httprequest/OnGetVouchersListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_GetCartGiftList
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    AddCartGift
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnGetVoucherAvailableInfoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_AddCartGift
        (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    ChangeCartGiftNumber
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILcom/qpidnetwork/livemodule/httprequest/OnGetVoucherAvailableInfoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_ChangeCartGiftNumber
        (JNIEnv *, jclass, jstring, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    RemoveCartGift
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnGetVoucherAvailableInfoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_RemoveCartGift
        (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    CheckOutCartGift
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnGetVoucherAvailableInfoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_CheckOutCartGift
        (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower
 * Method:    CreateGiftOrder
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnGetVoucherAvailableInfoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniGiftFlower_CreateGiftOrder
        (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
