/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni */

#ifndef _Included_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
#define _Included_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
#ifdef __cplusplus
extern "C" {
#endif
#undef com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_InvalidRequestId
#define com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_InvalidRequestId -1i64
/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    SetLogDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetLogDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    SetVersionCode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetVersionCode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    SetCookiesDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetCookiesDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    SetWebSite
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetWebSite
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    SetPublicWebSite
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetPublicWebSite
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    SetChangeSite
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetChangeSite
        (JNIEnv *, jclass, jstring);


/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    SetAuthorization
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetAuthorization
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    CleanCookies
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_CleanCookies
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    GetCookies
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_GetCookies
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    GetCookiesItem
 * Signature: ()["com/qpidnetwork/request/item/CookiesItem";
 */
JNIEXPORT jobjectArray JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_GetCookiesItem
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    GetCookiesInfo
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_GetCookiesInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    StopRequest
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_StopRequest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    StopAllRequest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_StopAllRequest
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    GetDeviceId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_GetDeviceId
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    SetDeviceId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetDeviceId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    GetDownloadContentLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_GetDownloadContentLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    GetRecvLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_GetRecvLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    GetUploadContentLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_GetUploadContentLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
 * Method:    GetSendLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_GetSendLength
  (JNIEnv *, jclass, jlong);

  /*
   * Class:     com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni
   * Method:    SetCookiesInfo
   * Signature: ([Ljava/lang/String;)V
   */
  JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetCookiesInfo
    (JNIEnv *, jclass, jobjectArray);

   /*
    * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
    * Method:    SetProxy
    * Signature: (Ljava/lang/String;I)V
    * add by Jagger 2018-2-22
    */
   JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetProxy
     (JNIEnv *, jclass, jstring);

     /*
      * Class:     com_qpidnetwork_livemodule_httprequest_RequestJni
      * Method:    SetAppId
      * Signature: (Ljava/lang/String;)V
      */
      JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livechathttprequest_LCRequestJni_SetAppId
        (JNIEnv *, jclass, jstring);


#ifdef __cplusplus
}
#endif
#endif
