/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_livemodule_httprequest_RequestJniSayHi */

#ifndef _Included_com_qpidnetwork_livemodule_httprequest_RequestJniSayHi
#define _Included_com_qpidnetwork_livemodule_httprequest_RequestJniSayHi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniSayHi
 * Method:    GetSayHiResourceConfig
 * Signature: (Lcom/qpidnetwork/livemodule/httprequest/OnGetSayHiResourceConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniSayHi_GetSayHiResourceConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniSayHi
 * Method:    GetSayHiAnchorList
 * Signature: (Lcom/qpidnetwork/livemodule/httprequest/OnGetSayHiAnchorListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniSayHi_GetSayHiAnchorList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniSayHi
 * Method:    IsCanSendSayHi
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnIsCanSendSayHiCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniSayHi_IsCanSendSayHi
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniSayHi
 * Method:    SendSayHi
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnSendSayHiCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniSayHi_SendSayHi
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniSayHi
 * Method:    GetAllSayHiList
 * Signature: (IILcom/qpidnetwork/livemodule/httprequest/OnGetAllSayHiListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniSayHi_GetAllSayHiList
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniSayHi
 * Method:    GetResponseSayHiList
 * Signature: (IIILcom/qpidnetwork/livemodule/httprequest/OnGetResponseSayHiListCallbackk;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniSayHi_GetResponseSayHiList
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniSayHi
 * Method:    GetSayHiDetail
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/livemodule/httprequest/OnGetSayDetailCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniSayHi_GetSayHiDetail
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_httprequest_RequestJniSayHi
 * Method:    ReadSayHiResponse
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/livemodule/httprequest/OnReadSayHiResponseCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_httprequest_RequestJniSayHi_ReadSayHiResponse
  (JNIEnv *, jclass, jstring, jstring, jobject);


#ifdef __cplusplus
}
#endif
#endif
