/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_livemodule_livemessage_LMClient */

#ifndef _Included_com_qpidnetwork_livemessage_LMClient
#define _Included_com_qpidnetwork_livemessage_LMClient
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_qpidnetwork_livemodule_im_IMClient
 * Method:    IMSetLogDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_LMSetLogDirectory
        (JNIEnv *, jclass, jstring);


/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    CreateLMManager
 * Signature: (Ljava/lang/String;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_InitLMManager
(JNIEnv *, jclass, jstring, jintArray, jlong , jobject, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    ReleaseLMManager
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_ReleaseLMManager
        (JNIEnv *, jclass);

///*
// * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
// * Method:    init
// * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/livemodule/livemessage/item/LMClientListener;[I)Z
// */
//JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_Init
//  (JNIEnv *, jclass, jlong , jobject);

///*
// * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
// * Method:    OnLoginHandle
// * Signature: (ZLjava/lang/String;Ljava/lang/String;)Z
// */
//JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_OnLoginHandle
//        (JNIEnv *, jclass, jboolean, jstring, jstring);
//
///*
// * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
// * Method:    OnLoginHandle
// * Signature: (Z)Z
// */
//JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_OnLogoutHandle
//        (JNIEnv *, jclass, jboolean, jstring, jstring);
/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    GetLocalPrivateMsgFriendList
 * Signature: ()[Lcom/qpidnetwork/livemodule/livemessage/item/LMPrivateMsgContactItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_GetLocalPrivateMsgFriendList
        (JNIEnv *, jclass);
/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:   GetPrivateMsgFriendList
 * Signature: ()J
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_GetPrivateMsgFriendList
        (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    GetLocalPrivateMsgFriendList
 * Signature: ()[Lcom/qpidnetwork/livemodule/livemessage/item/LMPrivateMsgContactItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_GetLocalFollowPrivateMsgFriendList
        (JNIEnv *, jclass);
/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:   GetPrivateMsgFriendList
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_GetFollowPrivateMsgFriendList
        (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    AddPrivateMsgLiveChatList
 * Signature: (Ljava/lang/String;)Z;
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_AddPrivateMsgLiveChatList
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    RemovePrivateMsgLiveChatList
 * Signature: (Ljava/lang/String;)Z;
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_RemovePrivateMsgLiveChatList
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    GetLocalPrivateMsgWithUserId
 * Signature: (Ljava/lang/String;)[Lcom/qpidnetwork/livemodule/livemessage/item/LiveMessageItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_GetLocalPrivateMsgWithUserId
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:   RefreshPrivateMsgWithUserId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_RefreshPrivateMsgWithUserId
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    GetMorePrivateMsgWithUserId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_GetMorePrivateMsgWithUserId
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    SetPrivateMsgReaded
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_SetPrivateMsgReaded
        (JNIEnv *, jclass, jstring, jobject);
/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    SendPrivateMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/qpidnetwork/livemodule/livemessage/item/LiveMessageItem;
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_SendPrivateMessage
        (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_qpidnetwork_livemodule_livemessage_LMClient
 * Method:    RepeatSendPrivateMsg
 * Signature: (Ljava/lang/String;I)Lcom/qpidnetwork/livemodule/livemessage/item/LiveMessageItem;
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_livemodule_livemessage_LMClient_RepeatSendPrivateMsg
        (JNIEnv *, jclass, jstring, jint);


#ifdef __cplusplus
}
#endif
#endif
