/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qdating_utils_LSUtilTesterJni */

#ifndef _Included_net_qdating_utils_LSUtilTesterJni
#define _Included_net_qdating_utils_LSUtilTesterJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qdating_utils_LSUtilTesterJni
 * Method:    Test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_qdating_utils_LSUtilTesterJni_Test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
