/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_httprequest_RequestJniLiveShow */

#ifndef _Included_com_qpidnetwork_httprequest_RequestJniLiveShow
#define _Included_com_qpidnetwork_httprequest_RequestJniLiveShow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    CreateLiveRoom
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/httprequest/OnCreateLiveRoomCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_CreateLiveRoom
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    GetCreatedLiveRoom
 * Signature: (Lcom/qpidnetwork/httprequest/OnCreateLiveRoomCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_GetCreatedLiveRoom
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    CloseLiveRoom
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_CloseLiveRoom
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    GetLimitAudienceListInRoom
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/httprequest/OnGetAudienceListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_GetLimitAudienceListInRoom
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    GetPagingAudienceListInRoom
 * Signature: (Ljava/lang/String;IILcom/qpidnetwork/httprequest/OnGetAudienceListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_GetPagingAudienceListInRoom
  (JNIEnv *, jclass, jstring, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    GetHotLiveList
 * Signature: (IILcom/qpidnetwork/httprequest/OnGetLiveRoomListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_GetHotLiveList
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    GetAllGiftList
 * Signature: (Lcom/qpidnetwork/httprequest/OnGetAllGiftCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_GetAllGiftList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    GetSendableGiftList
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/httprequest/OnGetSendableGiftListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_GetSendableGiftList
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    GetGiftDetail
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/httprequest/OnGetGiftDetailCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_GetGiftDetail
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    GetLiveCoverPhotoList
 * Signature: (Lcom/qpidnetwork/httprequest/OnGetLiveCoverPhotoListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_GetLiveCoverPhotoList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    AddLiveCoverPhoto
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_AddLiveCoverPhoto
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    SetDefaultUsedCoverPhoto
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_SetDefaultUsedCoverPhoto
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniLiveShow
 * Method:    DeleteLiveCoverPhoto
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniLiveShow_DeleteLiveCoverPhoto
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
