/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_httprequest_RequestJniUserInfo */

#ifndef _Included_com_qpidnetwork_httprequest_RequestJniUserInfo
#define _Included_com_qpidnetwork_httprequest_RequestJniUserInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_httprequest_RequestJniUserInfo
 * Method:    GetUserPhotoInfo
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/httprequest/OnGetUserPhotoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniUserInfo_GetUserPhotoInfo
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniUserInfo
 * Method:    GetUserProfile
 * Signature: (Lcom/qpidnetwork/httprequest/OnGetProfileCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniUserInfo_GetUserProfile
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniUserInfo
 * Method:    EditUserProfile
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Lcom/qpidnetwork/httprequest/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniUserInfo_EditUserProfile
  (JNIEnv *, jclass, jstring, jstring, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
