/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_httprequest_RequestJniOther */

#ifndef _Included_com_qpidnetwork_httprequest_RequestJniOther
#define _Included_com_qpidnetwork_httprequest_RequestJniOther
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_httprequest_RequestJniOther
 * Method:    SynConfig
 * Signature: (Lcom/qpidnetwork/httprequest/OnSynConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniOther_SynConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_httprequest_RequestJniOther
 * Method:    UploadPicture
 * Signature: (ILjava/lang/String;Lcom/qpidnetwork/httprequest/OnUploadPictureCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_httprequest_RequestJniOther_UploadPicture
  (JNIEnv *, jclass, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
