/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qdating_filter_LSImageUtilJni */

#ifndef _Included_net_qdating_filter_LSImageUtilJni
#define _Included_net_qdating_filter_LSImageUtilJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qdating_filter_LSImageUtilJni
 * Method:    GLReadPixels
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_net_qdating_filter_LSImageUtilJni_GLReadPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
