/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qdating_publisher_LSPublisherJni */

#ifndef _Included_net_qdating_publisher_LSPublisherJni
#define _Included_net_qdating_publisher_LSPublisherJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    SetLogDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_SetLogDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    SetLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_SetLogLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    Create
 * Signature: (Lnet/qdating/publisher/ILSPublisherCallbackJni;ZLnet/qdating/publisher/ILSVideoHardEncoderJni;IIIII)J
 */
JNIEXPORT jlong JNICALL Java_net_qdating_publisher_LSPublisherJni_Create
  (JNIEnv *, jobject, jobject, jboolean, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_Destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    PublishUrl
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_qdating_publisher_LSPublisherJni_PublishUrl
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    PushVideoFrame
 * Signature: (J[BIII)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_PushVideoFrame
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    PausePushVideo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_PausePushVideo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    ResumePushVideo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_ResumePushVideo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    PushAudioFrame
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_PushAudioFrame
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    ChangeVideoRotate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_ChangeVideoRotate
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_qdating_publisher_LSPublisherJni
 * Method:    Stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_qdating_publisher_LSPublisherJni_Stop
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
