platform :ios, '8.0'

#使用动态连接
#use_frameworks!

def shared_pods
	pod 'GPUImage', '0.1.7'
	pod 'AFNetworking', '3.0.4'
	pod 'SDWebImage', '4.3.0'
	pod 'Masonry', '0.6.4'
	pod 'YYText', '1.0.7'
	pod 'SDWebImage/WebP'
	pod "GCDWebServer/WebDAV", "~> 3.0"

end

target 'livestream_anchor' do
	shared_pods
	#pod 'MobileVLCKit', '2.2.2'
	pod "GCDWebServer/WebDAV", "~> 3.0"
end