/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_im_IMClient */

#ifndef _Included_com_qpidnetwork_im_IMClient
#define _Included_com_qpidnetwork_im_IMClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    init
 * Signature: ([Ljava/lang/String;Lcom/qpidnetwork/im/listener/IMClientListener;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_init
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    GetReqId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_im_IMClient_GetReqId
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    IsInvalidReqId
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_IsInvalidReqId
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_Login
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    Logout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_Logout
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    GetUser
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qpidnetwork_im_IMClient_GetUser
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    FansRoomIn
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_FansRoomIn
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    FansRoomOut
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_FansRoomOut
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    GetRoomInfo
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_GetRoomInfo
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    AnchorForbidMessage
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_AnchorForbidMessage
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    AnchorKickOffAudience
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_AnchorKickOffAudience
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    SendRoomMsg
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_SendRoomMsg
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    SendLikeEvent
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_SendLikeEvent
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    SendGift
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_SendGift
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring, jstring, jint, jboolean, jint, jint, jint);

/*
 * Class:     com_qpidnetwork_im_IMClient
 * Method:    SendBarrage
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_im_IMClient_SendBarrage
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
